name: npm-publish

on:
  release:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run linting and tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run prettier-check

      - name: Run tests
        run: npm run test

      - name: Publish on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
