name: run-tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run linting and tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run prettier-check

      - name: Run tests
        run: npm run test
